id: 'CAT-MIP-000000332'
term: Package
version: 1.0
authors:
  -
    name: Nicole Reineke
    github: nicole
    org: 'N-able'
discussion: 
categories:
  - Core
tags:
  - 'cat-mip'
  - core
  - msp
definition: 'A Package is a discrete unit of software that can be installed, upgraded, or removed on a device or system. It typically contains executable code, configuration files, and metadata needed to deploy software. Packages are distributed through package managers (e.g., MSI, RPM, DEB, EXE) and may represent full applications, libraries, agents, or drivers. In MSP environments, packages are often deployed via scripts, automation workflows, or remote management tools.

Code which is an update may also be referred to as a Patch.'
history:
  -
    date: '2025-08-07'
    author: nicole
    reason: Initial term addition to registry
  -
    date: '2025-08-07'
    author: nicole
    reason: 'Accepted into CAT-MIP registry'
synonyms:
  - Deployment Artifact
  - Installer
  - Module (when part of a larger software system)
  - Patch (when part of an explicit update to deployed software)
  - Software Package
relationships:
  - Package hasVersion
  - Package installs Software
  - Package isDeployedTo Device
  - Package isHostedIn Repository
  - Package isManagedBy Script or Automation Policy
  - Package isSignedBy Vendor
prompt_examples:
  - "Has the antivirus agent package been successfully installed on device 'HR-LT-002'?"
  - Install the package for Microsoft Edge on all Windows 11 devices.
  - "Which packages are waiting to be deployed on the 'Sales-Laptops' site?"
agent_execution:
  interpretation: 'When a prompt refers to a "Package," the AI agent will'
  actions:
    - Log the outcome and update inventory or compliance records
    - 'Look up package metadata, including name, version, and vendor signature'
    - 'Trigger installation, upgrade, rollback, or removal actions'
    - 'Validate compatibility with the target device (e.g., OS, architecture)'
